version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=amigoscode
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=customer
      - PGDATA=/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    volumes: 
      - db:/data/postgres
volumes:
    db:
networks:
  db:
    driver: bridge